version: '3.8'

services:
  # Microservice de factorisation symbolique
  symbolic-factorization-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symbolic-factorization-service
    ports:
      - "8082:8080"
    networks:
      - backend

  # Base de données MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=polynomial_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
